server:
  port: 8080
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

spring:
  profiles:
    active: pg
  main:
    banner-mode: "off"

---

spring:
  profiles: h2
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  datasource:
    name: test
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:testDB;INIT=CREATE SCHEMA IF NOT EXISTS inventory"
    username: sa
    password: sa
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/inventory-master.json"
    url: "jdbc:h2:mem:testDB;INIT=CREATE SCHEMA IF NOT EXISTS liquibase"
    user: sa
    password: sa
    default-schema: liquibase

---

spring:
  profiles: pg
  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  datasource:
    name: postgres
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/erp"
    username: pibity
    password: password
  liquibase:
    enabled: false
    change-log: "classpath:/db/changelog/inventory-master.json"
    url: "jdbc:postgresql://localhost:5432/erp"
    user: pibity
    password: password
    default-schema: liquibase
logging:
  level:
    org.hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
    liquibase: INFO
    org.keycloak: DEBUG
