server:
  port: 8080
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

spring:
  profiles:
    active: pg
  main:
    banner-mode: off
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

---

spring:
  profiles: pg
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  datasource:
    name: postgres
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/erp"
    username: pibity
    password: password
  liquibase:
    enabled: false
    change-log: "classpath:/db/changelog/inventory-master.json"
    url: "jdbc:postgresql://localhost:5432/erp"
    user: pibity
    password: password
    default-schema: liquibase
logging:
  level:
    org.hibernate:
      SQL: debug
      type:
        descriptor:
          sql: trace
    liquibase: INFO
    org.keycloak: DEBUG
